---
- name: Remove template sudo config (if existent)
  file:
    path: /etc/sudoers.d/splunk-admin
    state: absent

- name: Add app config for sudo
  copy:
    src: "{{ repo_base }}/common/sudo/cribl-admin"
    dest: /etc/sudoers.d/cribl-admin
    mode: 0600
