---
- name: Push installation package
  copy:
    src: "{{ repo_base }}/common/packages/cribl/{{ logstream_installation.package_file }}"
    dest: "/{{ logstream_installation.remote_package_temp_path }}/{{ logstream_installation.package_file }}"
    mode: 600
