---

# splunk
splunk_ulimit_nofile_softhard: 65536
splunk_ulimit_nproc_soft: 16000
splunk_ulimit_nproc_hard: 16000
splunk_ulimit_fsize_soft: unlimited
splunk_ulimit_fsize_hard: unlimited
splunk_ulimit_data_soft: unlimited
splunk_ulimit_data_hard: unlimited

# logstream
logstream_ulimit_nofile_softhard: 65536
logstream_ulimit_nproc_soft: 16000
logstream_ulimit_nproc_hard: 16000
logstream_ulimit_fsize_soft: unlimited
logstream_ulimit_fsize_hard: unlimited
logstream_ulimit_data_soft: unlimited
logstream_ulimit_data_hard: unlimited
