---

- name: Create {{ user_name }} unix group
  group:
    name: "{{ user_name }}"
    state: present

- name: Create {{ appadm }} group
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ appadm.split(',') }}"
  when: appadm is defined

- name: Create {{ user_name }} unix user
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    create_home: yes
    skeleton: /etc/skel
    append: yes
    comment: "created by Ansible"
    shell: "/bin/bash"
    password: "{{ user_pass | password_hash('sha512') }}"
    expires: -1
    state: present

- name: Disable password expiry for {{ user_name }}
  shell: "passwd -x -1 {{ user_name }}"

- name: Add { user_name }} to additional groups
  user:
    name: "{{ user_name }}"
    groups: "{{ item }}"
    append: yes
    state: present
  loop: "{{ appadm.split(',') }}"
  when: appadm is defined
