---

- name: Ensure temp dir is there
  file:
    path: "{{ pors_temp_dir }}"
    state: directory

- name: Clean old var file
  file:
    path: "{{ pors_temp_dir }}/ansible_{{ varname }}.var"
    state: absent

- name: Fill template
  template:
    src: getvar.yml.j2
    dest: "{{ pors_temp_dir }}/getvar.yml"
    mode: 0640

- include: "{{ pors_temp_dir }}/getvar.yml"

- name: Write variable
  lineinfile:
    path: "{{ pors_temp_dir }}/ansible_{{ varname }}.var"
    line: "{{ item.value }}"
    create: yes
  loop: "{{ lookup('dict',parsed_var) }}"
  when:
    - item.key != "changed"
    - item.key != "failed"
