- name: Settle up the base
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free

  roles:
    - system_upgrade
      when: system.upgrade_os is defined and system.upgrade_os == True
    - system_kernel
    - system_base
    - system_optimize
    - system_ntp
    - system_journal
