---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

# touch 

- name: "Touch server.conf"
  file:
    path: "{{ splunk_conf_path }}/server.conf"
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_group }}"
    mode: 600 
    state: touch
  changed_when: false
