---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

#####################################################################################################################
# [clustering]
#####################################################################################################################

# site_replication_factor

- name: "Configure server.conf [clustering] - site_search_factor state=present"
  ini_file: 
    dest: "{{ splunk_conf_path }}/server.conf"
    section: clustering
    option: site_search_factor
    value: "{{ splunk_server_conf.clustering.site_search_factor }}"
    state: present
  when: splunk_server_conf.clustering.site_search_factor is defined
  notify: splunk restart

- name: "Configure server.conf [clustering] - site_search_factor state=absent (default)"
  ini_file: 
    dest: "{{ splunk_conf_path }}/server.conf"
    section: clustering
    option: site_search_factor
    state: absent
  when: splunk_server_conf.clustering.site_search_factor is undefined
  notify: splunk restart

