---
- name: Check if custom authorized_keys exists
  become: yes
  become_user: "{{ system_shared_service_account }}"
  stat:
      path: "{{ splunk_repository.repository_root }}/authorized_keys_{{ system_shared_service_account }}"
  register: stat_auth_file
  when: system_shared_service_account is defined

- name: "Set/Update authorized keys for {{ system_shared_service_account }}"
  become: yes
  become_user: "{{ system_shared_service_account }}"
  authorized_key:
    user: "{{ system_shared_service_account }}"
    state: present
    key: "{{ lookup('file', '{{ splunk_repository.repository_root }}/authorized_keys_{{ system_shared_service_account }}') }}"
  when: stat_auth_file.stat.exists is defined and system_shared_service_account is defined
