---
#####################################################################################################################
# Configurations for Splunk server.conf
####################################################################################################################

splunk_server_conf:
  clustering:
    mode: master
    pass4SymmKey: "{{ vault_idxclustering_pass4SymmKey }}"
    multisite: true
    cluster_label: "{{ target_env }}"
    available_sites: "{{ idx_cluster_available_sites }}"
    replication_factor: "{{ idx_cluster_replicationfactor }}"
    search_factor: "{{ idx_cluster_searchfactor }}"
    site_replication_factor: "{{ idx_cluster_site_replicationfactor }}"
    site_search_factor: "{{ idx_cluster_site_searchfactor }}"
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
    site: site1
  sslConfig:
    sslRootCAPath: $SPLUNK_HOME/etc/auth/cacert.pem
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
  license:
    master_uri: dynamic
  indexer_discovery:
    pass4SymmKey: "{{ vault_indexerdiscovery_pass4SymmKey }}"
