---
- hosts: pors_server

  tasks:

  - name: Check/Create repo dir
    file:
        path: "{{ repo_base }}/common/packages/splunk"
        state: directory

  - name: Download Splunk tgz packages
    get_url: url="{{ item.value.url }}"
             dest="{{ repo_base }}/common/packages/splunk"
             owner={{ splunk_repository.repository_owner }}
             group={{ splunk_repository.repository_group }}
             mode=644
    with_dict: "{{ splunk_packages.linux_64_tgz }}"
    when: splunk_installation.package_format == "tgz" and
          splunk_packages.linux_64_tgz is defined


