- name: Base setup
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: True
  strategy: free

- include: ../shelper/ae_install_shelper.yml
  when: shelper_installation.enabled

- name: Install Splunk on all hosts
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: True
  strategy: free

  vars:
    splunk_upgrade: False

  roles:
    - install
