---
- name: Upgrade System
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  tasks:
    - debug:
        var: system.upgrade_os

    - import_role:
        name: system_base
      when: system.upgrade_os is defined and system.upgrade_os == True

- name: Upgrade Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  #do NOT use no_log: True here as it will be effective for all sub tasks then
  gather_facts: True

  vars:
    splunk_upgrade: True
    splunk_type: "splunk"

  roles:
    - splunk_info
    - install

- include: ../shelper/ae_install_shelper.yml
  when: shelper_installation.enabled
