---
- hosts: pors_server
  tasks:

  - name: Check/Create repo dir
    file:
        path: "{{ repo_base }}/common/packages/cribl"
        state: directory

  - name: Download logstream package
    get_url: url="{{ item.value.url }}"
             dest={{ repo_base }}/common/packages/cribl
             owner={{ splunk_repository.repository_owner }}
             group={{ splunk_repository.repository_group }}
             mode=644
    with_dict: "{{ logstream_packages.linux_64_tgz }}"
    when: logstream_packages.linux_64_tgz is defined
