- name: Install cribl logstream
  hosts: "*:!pors_server"
  remote_user: "{{ cribl_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: true
  strategy: free

  vars:
    logstream_upgrade: False

  roles:
    - install_logstream

- include: ../system/ae_system_base.yml
