---
####################################################################################################################
#
# ALL OUTCOMMENTED KEY:VALUES (IF ANY) YOU SEE HERE ARE THE DEFINED DEFAULT VALUES
# i.e. there is no need to enable them if you like the shown default value
#
####################################################################################################################

#####################################################################################################################
# Configurations for Splunk deployment directory
# Keep in mind to replace "-" and "/" with an underscore "_"
#####################################################################################################################

# default directory to put splunk apps in (i.e {splunk install dir}/etc/<this-var>)
# must be overwritten in a group_vars/deploymentserver, ..., etc
#deployment:
#    dir: apps
