---
####################################################################################################################
#
# ALL OUTCOMMENTED KEY:VALUES (IF ANY) YOU SEE HERE ARE THE DEFINED DEFAULT VALUES
# i.e. there is no need to enable them if you like the shown default value
#
####################################################################################################################

#####################################################################################################################
# Configurations for Splunk distsearch.conf
####################################################################################################################

# usually should not touched
#splunk_distsearch_conf:
#    distributedSearch:
#      servers: 
#        - "{{ groups.peernode }}"
