---
####################################################################################################################
#
# ALL OUTCOMMENTED KEY:VALUES (IF ANY) YOU SEE HERE ARE THE DEFINED DEFAULT VALUES
# i.e. there is no need to enable them if you like the shown default value
#
####################################################################################################################

#####################################################################################################################
# Configurations for Splunk outputs.conf
#####################################################################################################################

# outputs.conf
splunk_outputs_conf:
  tcpout:
    defaultGroup: "{{ target_env }}"
    target_group:
      # change to the above defaultGroup - usually your target_env (production,staging,development)
      staging:
        useACK: true
        indexerDiscovery: "{{ target_env }}"
        sslPassword: "{{ vault_tcpout_sslPassword }}"
        sslCertPath: $SPLUNK_HOME/etc/auth/server.pem
        sslRootCAPath: $SPLUNK_HOME/etc/auth/ca.pem
  indexer_discovery:
    # change to the above indexerDiscovery value - usually your target_env (production,staging,development)
    staging:
      pass4SymmKey: "{{ vault_indexerdiscovery_pass4SymmKey }}"
      master_uri: dynamic
