---
####################################################################################################################
#
# ALL OUTCOMMENTED KEY:VALUES (IF ANY) YOU SEE HERE ARE THE DEFINED DEFAULT VALUES
# i.e. there is no need to enable them if you like the shown default value
#
####################################################################################################################

######################################################################
# Configure PORS
######################################################################

# the user and group PORS is running as
#pors_user: pors
#pors_group: pors

# PORS installation dir
#base_install_dir: /opt/pors

# PORS remote SSH user (which connects to any managed system)
#pors_ssh_user: ansible

# TEMP directory for various tasks
#pors_temp_dir: /tmp/pors

# PORS data directory. Changing this might require other changes as well (e.g. ~/.pors/vars)
# It is NOT recommended to change the default value.
#pors_data_dir: /opt/pors_data

# custom directory for playbooks
#custom_playbook_dir: "{{ pors_data_dir }}/custom/playbooks"

# PORS expects the data directory to be a git repo as all changes will be tracked
# and commited. Besides that you can specify to push changes to the configured
# git server automatically which is HIGHLY recommended. This way you have a backup
# of all the important custom changes and the whole environment.
# You have to init the directory with your git server and remote repo manually:
# <create a pors_data repo in your git server>
# cd /opt/pors_data
# git init
# git branch -m main
# git remote add origin <REPO-URL>
#git_pors_data_push: no

# Set a name to identify this ansible instance
# (deprecated but must be set atm, identifier for init lines and such
# can be anything you like to identify this PORS server)
ansible_conf:
  host: <SET-HOSTNAME>
