---
#####################################################################################################################
# Configurations for Splunk server.conf
#####################################################################################################################

splunk_server_conf:
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
  license:
    master_uri: dynamic
  sslConfig:
    sslRootCAPath: $SPLUNK_HOME/etc/auth/cacert.pem
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
  indexer_discovery:
    pass4SymmKey: "{{ vault_indexerdiscovery_pass4SymmKey }}"
