---
####################################################################################################################
#
# ALL OUTCOMMENTED KEY:VALUES (IF ANY) YOU SEE HERE ARE THE DEFINED DEFAULT VALUES
# i.e. there is no need to enable them if you like the shown default value
#
####################################################################################################################

#####################################################################################################################
# Installation Variables
# should be set in your VAULT only. Check documentation.
#####################################################################################################################

#splunk_auth:
#  admin_password: "{{ vault_splunk_admin_password }}"
#  splunk_secret: "{{ vault_splunk_secret }}"
