---
#####################################################################################################################
# Configurations for Splunk web.conf
#####################################################################################################################

#####################################################################################################################
# [settings]
#####################################################################################################################

# enableSplunkWebSSL

- name: "Configure web.conf [settings] - enable_insecure_pdfgen: state=present"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings option=enable_insecure_pdfgen
            value={{ splunk_web_conf.settings.enable_insecure_pdfgen }}
            state=present
  when: splunk_web_conf.settings.enable_insecure_pdfgen is defined and
        splunk_web_conf.settings.enable_insecure_pdfgen == true
  notify: splunk restart

- name: "Configure web.conf [settings] - enable_insecure_pdfgen state=absent (default)"
  ini_file: dest="{{ splunk_conf_path }}/web.conf"
            section=settings
            option=enable_insecure_pdfgen
            state=absent
  when:  splunk_web_conf.settings.enable_insecure_pdfgen is undefined or 
         splunk_web_conf.settings.enable_insecure_pdfgen == false
  notify: splunk restart
