---
#####################################################################################################################
# Configurations for Splunk server.conf
####################################################################################################################

splunk_server_conf:
  general:
    pass4SymmKey: "{{ vault_general_pass4SymmKey }}"
    site: site1
  license:
    master_uri: dynamic
  clustering:
    mode: searchhead
    master_uri: dynamic
    multisite: True
    pass4SymmKey: "{{ vault_idxclustering_pass4SymmKey }}"
  shclustering:
    mgmt_uri: dynamic
    conf_deploy_fetch_url: dynamic
    # DEPRECATED: conf_deploy_fetch_url: https://yourdeployer:8089
    # OPTIONAL: Unique identifier for this cluster as a whole, shared across all cluster:
    #id: <GUID>
    shcluster_label: "shc_{{ target_env }}"
    pass4SymmKey: "{{ vault_shclustering_pass4SymmKey }}"
    mode: member
    artifact_status_fields: user,app,label,max_time
    scheduling_heuristic: round_robin
    replication_factor: 3
    disabled: False
  replication_port_ssl:
    port: 9888
    serverCert: $SPLUNK_HOME/etc/auth/server.pem
    sslPassword: "{{ vault_replication_port_sslPassword }}"
    disabled: false
  sslConfig:
    sslRootCAPath: $SPLUNK_HOME/etc/auth/cacert.pem
    sslPassword: "{{ vault_sslConfig_sslPassword }}"
  indexer_discovery:
    pass4SymmKey: "{{ vault_indexerdiscovery_pass4SymmKey }}"
