---
- include: update.yml
  when: 
    - system.upgrade_os is defined and system.upgrade_os == True
    - ansible_facts['os_family'] == "RedHat"

- include: add_elrepo.yml
  when:
    - system_yum.elrepo.enabled is defined and system_yum.elrepo.enabled == True
    - ansible_facts['os_family'] == "RedHat"

- include: install_elrepo_kernel.yml
  when:
    - system_yum.elrepo.kernel.setup == "yes"
    - ansible_facts['os_family'] == "RedHat"
