---

# check for existence of splunk init file
- stat: path=/etc/init.d/splunk
  register: splunkinitfile

# file attr doesnt work and is available in ansible version >= v2.3 only
- name: Remove protection from splunk init.d script
  shell: chattr -i /etc/init.d/splunk
  when: splunkinitfile is defined and splunkinitfile.stat.exists and run_in_docker.rc == 1

- name: Tune splunk init.d script (header)
  blockinfile:
        dest: "/etc/init.d/splunk"
        marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK - INFO -->"
        insertbefore: "RETVAL=0"
        block: |
           # ----------------------------------------------------------------------------------------
           # THIS SCRIPT IS PROTECTED BY THE IMMUTABLE BIT TO AVOID ACCIDENTALLY OVERWRITING!
           # 
           # Last modification: {{ ansible_date_time.date }} by {{ ansible_conf.host }}
           # 
           # TO MODIFY: chattr -i
           # TO PROTECT AGAIN: chattr +i
           #
           # or just use the following one liner:
           # chattr -i /etc/init.d/splunk && vim /etc/init.d/splunk && chattr +i /etc/init.d/splunk
           #
           # HINT: The above does not apply in docker due to the fact that attr will not work here
           # ----------------------------------------------------------------------------------------
        backup: yes
  when: "splunk_optimize.initd == true | default(false)"

- name: Tune splunk init.d script (ulimit 1/2)
  blockinfile:
        dest: "/etc/init.d/splunk"
        marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK - ULIMITS -->"
        insertafter: ". /etc/init.d/functions"
        block: |
            SPLUNKH=/opt/splunk
            echo "$(date) - splunk init start: nofiles soft $(ulimit -Sn)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init start: nofiles hard $(ulimit -Hn)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init start: no processes $(ulimit -u)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init start: max file size $(ulimit -f)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init start: data segment size $(ulimit -d)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            ulimit -Hn 65536
            ulimit -Sn 65536
            ulimit -u 16000
            ulimit -f unlimited
            ulimit -d unlimited
        backup: yes
  when: "splunk_optimize.initd == true | default(false)"

- name: Tune splunk init.d script (ulimit 2/2)
  blockinfile:
        dest: "/etc/init.d/splunk"
        marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK - ULIMITS-LOG -->"
        insertbefore: "exit .RETVAL"
        block: |
            echo "$(date) - splunk init end : nofiles soft $(ulimit -Sn)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init end : nofiles hard $(ulimit -Hn)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init end : no processes $(ulimit -u)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init end : max file size $(ulimit -f)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
            echo "$(date) - splunk init end : data segment size $(ulimit -d)" >> $SPLUNKH/var/log/splunk/splunk-init-ulimit.log
        backup: yes
  when: "splunk_optimize.initd == true | default(false)"

# file attr doesnt work and is available in ansible version >= v2.3 only
- name: Protect splunk init.d script again
  shell: chattr +i /etc/init.d/splunk
  when: 
    - "run_in_docker.rc != 0"
    - "splunk_optimize.initd == true | default(false)"

- name: Reload init.d conf
  shell: systemctl daemon-reload
  when: 
    - "run_in_docker.rc == 1"
    - "splunk_optimize.initd == true | default(false)"

