---
- name: Set ulimit (nofile,soft+hard)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: '-'
    limit_item: nofile
    value: "{{ splunk_ulimit_nofile_softhard }}"

- name: Set ulimit (nproc,soft)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: soft
    limit_item: nproc
    value: "{{ splunk_ulimit_nproc_soft }}"

- name: Set ulimit (nproc,hard)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: hard
    limit_item: nproc
    value: "{{ splunk_ulimit_nproc_hard }}"

- name: Set ulimit (fsize,soft)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: soft
    limit_item: fsize
    value: "{{ splunk_ulimit_fsize_soft }}"

- name: Set ulimit (fsize,hard)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: hard
    limit_item: fsize
    value: "{{ splunk_ulimit_fsize_hard }}"

- name: Set ulimit (data,soft)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: soft
    limit_item: data
    value: "{{ splunk_ulimit_data_soft }}"

- name: Set ulimit (data,hard)
  community.general.pam_limits:
    domain: "{{ splunk_install_user }}"
    limit_type: hard
    limit_item: data
    value: "{{ splunk_ulimit_data_hard }}"
