---
- name: Create Splunk unix group
  group: name=splunk
         state=present
  when: splunk_installation.package_format != "rpm"

- name: Create Splunk unix user
  user: name=splunk 
        group=splunk
        state=present
        comment="Splunk"
        shell="/bin/bash"
        home="{{ splunk_installation.splunk_home_path }}"
        password="!!"
  when: splunk_installation.package_format != "rpm"
