---
- name: Create Splunk unix group
  group:
    name: "{{ splunk_install_group }}"
    state: present
  when: splunk_installation.package_format != "rpm"

- name: Create Splunk unix user
  user:
    name: "{{ splunk_install_user }}"
    group: "{{ splunk_install_group }}"
    comment: "Splunk"
    shell: "/bin/bash"
    home: "{{ splunk_installation.splunk_home_path }}"
    password: "!!"
    state: present
  when: splunk_installation.package_format != "rpm"
