---

- name: Create common splunk.secret
  template:
    src: etc/auth/splunk.secret.j2
    dest: "{{ splunk_installation.splunk_home_path }}/etc/auth/splunk.secret"

- name: Set permissions for splunk.secret
  file:
    path: "{{ splunk_installation.splunk_home_path }}/etc/auth/splunk.secret"
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_group }}"
    mode: 0400

