---
- name: "Copy installation package ({{ splunk_type }})"
  copy:
    src: "{{ repo_base }}/common/packages/{{ splunk_type }}/{{ splunk_installation.package_file }}"
    dest: "/{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
    mode: 600
